---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/users":
    get:
      summary: get user list
      responses:
        '200':
          description: user list
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    email:
                      type: string
                  required:
                  - name
                  - email
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
